// Generated by gencpp from file slam_pkg/num2Response.msg
// DO NOT EDIT!


#ifndef SLAM_PKG_MESSAGE_NUM2RESPONSE_H
#define SLAM_PKG_MESSAGE_NUM2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_pkg
{
template <class ContainerAllocator>
struct num2Response_
{
  typedef num2Response_<ContainerAllocator> Type;

  num2Response_()
    : b(0)  {
    }
  num2Response_(const ContainerAllocator& _alloc)
    : b(0)  {
  (void)_alloc;
    }



   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::slam_pkg::num2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_pkg::num2Response_<ContainerAllocator> const> ConstPtr;

}; // struct num2Response_

typedef ::slam_pkg::num2Response_<std::allocator<void> > num2Response;

typedef boost::shared_ptr< ::slam_pkg::num2Response > num2ResponsePtr;
typedef boost::shared_ptr< ::slam_pkg::num2Response const> num2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_pkg::num2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_pkg::num2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_pkg::num2Response_<ContainerAllocator1> & lhs, const ::slam_pkg::num2Response_<ContainerAllocator2> & rhs)
{
  return lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_pkg::num2Response_<ContainerAllocator1> & lhs, const ::slam_pkg::num2Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::slam_pkg::num2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_pkg::num2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_pkg::num2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_pkg::num2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_pkg::num2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_pkg::num2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_pkg::num2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5a3c6284d5ab11e232db053f443f102";
  }

  static const char* value(const ::slam_pkg::num2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5a3c6284d5ab11eULL;
  static const uint64_t static_value2 = 0x232db053f443f102ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_pkg::num2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_pkg/num2Response";
  }

  static const char* value(const ::slam_pkg::num2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_pkg::num2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 b\n"
;
  }

  static const char* value(const ::slam_pkg::num2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_pkg::num2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_pkg::num2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_pkg::num2Response_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_PKG_MESSAGE_NUM2RESPONSE_H
