// Generated by gencpp from file slam_pkg/num2.msg
// DO NOT EDIT!


#ifndef SLAM_PKG_MESSAGE_NUM2_H
#define SLAM_PKG_MESSAGE_NUM2_H

#include <ros/service_traits.h>


#include <slam_pkg/num2Request.h>
#include <slam_pkg/num2Response.h>


namespace slam_pkg
{

struct num2
{

typedef num2Request Request;
typedef num2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct num2
} // namespace slam_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_pkg::num2 > {
  static const char* value()
  {
    return "f16097f93022db785b2cc9436c158893";
  }

  static const char* value(const ::slam_pkg::num2&) { return value(); }
};

template<>
struct DataType< ::slam_pkg::num2 > {
  static const char* value()
  {
    return "slam_pkg/num2";
  }

  static const char* value(const ::slam_pkg::num2&) { return value(); }
};


// service_traits::MD5Sum< ::slam_pkg::num2Request> should match
// service_traits::MD5Sum< ::slam_pkg::num2 >
template<>
struct MD5Sum< ::slam_pkg::num2Request>
{
  static const char* value()
  {
    return MD5Sum< ::slam_pkg::num2 >::value();
  }
  static const char* value(const ::slam_pkg::num2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_pkg::num2Request> should match
// service_traits::DataType< ::slam_pkg::num2 >
template<>
struct DataType< ::slam_pkg::num2Request>
{
  static const char* value()
  {
    return DataType< ::slam_pkg::num2 >::value();
  }
  static const char* value(const ::slam_pkg::num2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_pkg::num2Response> should match
// service_traits::MD5Sum< ::slam_pkg::num2 >
template<>
struct MD5Sum< ::slam_pkg::num2Response>
{
  static const char* value()
  {
    return MD5Sum< ::slam_pkg::num2 >::value();
  }
  static const char* value(const ::slam_pkg::num2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_pkg::num2Response> should match
// service_traits::DataType< ::slam_pkg::num2 >
template<>
struct DataType< ::slam_pkg::num2Response>
{
  static const char* value()
  {
    return DataType< ::slam_pkg::num2 >::value();
  }
  static const char* value(const ::slam_pkg::num2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_PKG_MESSAGE_NUM2_H
